/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Profiles */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profiles__profile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criteria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Criteria */
        get: operations["list_criteria_api_criteria_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_locations_get"];
        put?: never;
        /** Create Location */
        post: operations["create_location_api_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evaluation */
        post: operations["create_evaluation_api_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_api_evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Sensitivity */
        post: operations["run_sensitivity_api_evaluations__evaluation_id__sensitivity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}/comparison/{other_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comparison */
        get: operations["get_comparison_api_evaluations__evaluation_id__comparison__other_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Evaluation */
        get: operations["export_evaluation_api_evaluations__evaluation_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Перевірка доступності сервісу.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ComparisonRead
         * @description GET /api/evaluations/{id}/comparison/{otherId} — Spearman + per-location deltas.
         */
        ComparisonRead: {
            /** Spearmanrho */
            spearmanRho: number;
            /** Pairwisedifferences */
            pairwiseDifferences: components["schemas"]["PairwiseDifference"][];
        };
        /**
         * ConfidenceInterval
         * @description 95 % confidence interval for the closeness coefficient of one location.
         * Bounds are the 2.5/97.5 percentiles of the C* sample (2.3.3), so the interval is
         * generally asymmetric and `mean` does not equal the midpoint. Field names match Appendix A.9.
         */
        ConfidenceInterval: {
            /** Locationid */
            locationId: number;
            /** Mean */
            mean: number;
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
        };
        /**
         * CriterionRead
         * @description GET /api/criteria — one criterion in the catalog.
         */
        CriterionRead: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Optimizationtype */
            optimizationType: string;
            /** Scale */
            scale: string;
        };
        /**
         * CriterionWithWeight
         * @description Criterion as embedded inside a ProfileDetailRead (no unit/scale needed there).
         */
        CriterionWithWeight: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Weight */
            weight: number;
        };
        /**
         * EvaluationCreate
         * @description POST /api/evaluations — request body with profile and pairwise matrix.
         */
        EvaluationCreate: {
            /** Profileid */
            profileId: number;
            /** Pairwisematrix */
            pairwiseMatrix: components["schemas"]["FuzzyNumber"][][];
        };
        /**
         * EvaluationRead
         * @description GET /api/evaluations/{id} — full result of one MCDM run.
         */
        EvaluationRead: {
            /** Evaluationid */
            evaluationId: number;
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** Ranking */
            ranking: components["schemas"]["RankingItemRead"][];
            /** Executiontimems */
            executionTimeMs?: number | null;
        };
        /**
         * FuzzyNumber
         * @description Triangular fuzzy number (l, m, u) with l ≤ m ≤ u and m within Saaty bounds.
         */
        FuzzyNumber: {
            /** L */
            l: number;
            /** M */
            m: number;
            /** U */
            u: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LocationCreate
         * @description POST /api/locations request body.
         */
        LocationCreate: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /** District */
            district?: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /**
         * LocationRead
         * @description GET /api/locations element with lat/lon extracted from PostGIS geom.
         */
        LocationRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /** District */
            district?: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Criteriavalues */
            criteriaValues?: {
                [key: string]: number;
            } | null;
        };
        /**
         * PairwiseDifference
         * @description Per-location difference of two rankings.
         */
        PairwiseDifference: {
            /** Locationid */
            locationId: number;
            /** Ranka */
            rankA: number;
            /** Rankb */
            rankB: number;
            /** Delta */
            delta: number;
        };
        /**
         * ProfileDetailRead
         * @description GET /api/profiles/{id} — profile with attached criteria and pairwise matrix.
         */
        ProfileDetailRead: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Criteria
             * @default []
             */
            criteria: components["schemas"]["CriterionWithWeight"][];
            /** Pairwisematrix */
            pairwiseMatrix?: components["schemas"]["FuzzyNumber"][][] | null;
        };
        /**
         * ProfileRead
         * @description GET /api/profiles — list element.
         */
        ProfileRead: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * RankingItemRead
         * @description One row of the TOPSIS ranking, with renamed ORM fields for the JSON contract.
         */
        RankingItemRead: {
            /** Locationid */
            locationId: number;
            /** Rank */
            rank: number;
            /** Closeness */
            closeness: number;
            /** Splus */
            sPlus: number;
            /** Sminus */
            sMinus: number;
        };
        /**
         * SensitivityRead
         * @description Aggregated Monte Carlo result per Appendix A.9.
         * stabilityMatrix[locationId][k] = p_i(k) (formula 1.17) for k in {1, 3, 5}.
         * confidenceIntervals lists top-N alternatives ordered by mean C* descending.
         */
        SensitivityRead: {
            /** Stabilitymatrix */
            stabilityMatrix: {
                [locationId: string]: {
                    [k: string]: number;
                };
            };
            /** Confidenceintervals */
            confidenceIntervals: components["schemas"]["ConfidenceInterval"][];
        };
        /**
         * SensitivityRequest
         * @description POST /api/evaluations/{id}/sensitivity — MC parameters.
         */
        SensitivityRequest: {
            /**
             * Iterations
             * @default 10000
             */
            iterations: number;
            /**
             * Perturbation
             * @default 0.15
             */
            perturbation: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"][];
                };
            };
        };
    };
    get_profile_api_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_criteria_api_criteria_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionRead"][];
                };
            };
        };
    };
    list_locations_api_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"][];
                };
            };
        };
    };
    create_location_api_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_api_evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_api_evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_sensitivity_api_evaluations__evaluation_id__sensitivity_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensitivityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comparison_api_evaluations__evaluation_id__comparison__other_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: number;
                other_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_evaluation_api_evaluations__evaluation_id__export_get: {
        parameters: {
            query?: {
                format?: "csv" | "json";
            };
            header?: never;
            path: {
                evaluation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
